Added citation.cff for "cite" widget
catalystneuro/roiextractors pull request #89
Opened 2021-12-29 15:01 UTC by alejoe91

2021-12-30 23:05 UTC, bendichter commented on CITATION.cff
> +    given-names: Dichter
"family name" means last name and "given name" means first name. Also, for these types of things use Benjamin as my first name

2021-12-30 23:06 UTC, bendichter requested changes
"family name" means last name and "given name" means first name. Also, for these types of things use Benjamin as my first name

2022-01-03 08:10 UTC, alejoe91 commented
> "family name" means last name and "given name" means first name. Also, for these types of things use Benjamin as my first name

Oooops! I know but I did it quickly and got it worng. Fixing it now

2022-01-03 15:19 UTC, bendichter approved these changes

2022-02-02 08:59 UTC, merged